project_id = "elrfcqtfdiqevgvbwjac"

[functions.send-welcome-email]
verify_jwt = false

[functions.weekly-generate-drafts]
verify_jwt = false

[functions.weekly-generate-final]
verify_jwt = false

[functions.weekly-admin-inputs]
verify_jwt = false

[functions.weekly-publish]
verify_jwt = false

[functions.market-indexer]
verify_jwt = false

[functions.send-weekly-emails]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.attention-ingest]
verify_jwt = false